### ISSUE TITLE
Backend Layout "None" gives error in Frontend

### ISSUE THREAD

**Issue by riklamme** [georgringer/belayout_fileprovider#22]
We use your extension for a few project, great way of divining be layouts so we can put them in our git repo and provider extension.

But

Yesterday i saw an error when i choose de none option from the dropdown. Without this extension you can define a default value, with i guess is selected when there is no html found.

Yesterday i write a workaround so we dont see the error anymore.

``` javascript
lib.fluid = FLUIDTEMPLATE
lib.fluid {
    file.stdWrap.cObject >
    file.stdWrap.cObject = COA
    file.stdWrap.cObject {
        10 = TEXT
        10 {
            if {
                value.field = backend_layout
                equals = -1
            }
            wrap = {$settings.path.tmpl.layouts}/Header--Col_1.html
        }
        20 = TEXT
        20 {
            if {
                value.field = backend_layout
                equals = -1
                negate = 1
            }
            data = levelfield:-2,backend_layout_next_level,slide
            override.field = backend_layout
            split {
                token = file__
                1.current = 1
                1.wrap = |
            }
            wrap = {$settings.path.tmpl.layouts}/|.html
        }
    }

    # Define settings for use in Fluid
    settings {
    }
}
```

We use this in an provider extension, so thats the reason i clear the "file.stdWrap.cObject". 

My question, is this a know problem? is there a better solution?

**Comment by xperseguers** [comment]
You can easily handle the error by using the sample TS @georgringer is showing in the documentation and naming your HTML template file `-1.html`. I usually do that with a message explaining that the user should choose a backend layout :)
